// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package nbastats

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"per_mode": {
			Default:     "PerGame",
			Description: "per_mode determines if the stats to be queried should be the per game average or the cumulative totals",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"pollingPeriod": {
			Default:     "5m",
			Description: "how often the connector will get data from the url",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
	}
}
